### ISSUE TITLE
No tests ran result

### ISSUE THREAD

**Issue by crisAD** [jmcnamara/pytest_c_testrunner#3]
Hi,

I just pulled the repository and tried running the c_testrunner.
However, my ran resulted into a "No Tests Ran"
What do you think is the problem?

I did not do anything, I was just simply running pytest.
My pytest version is 3.1.2 and my python version is 3.5.2 running on anaconda version 2.5.0 (32-bit)

Thanks.

**Comment by jmcnamara** [comment]
This plugin was written a few years ago and I don't think it included support for Python 3 at the time. I'll look into bringing it up to date.

**Comment by crisAD** [comment]
That would be great!
Thanks!

**Comment by jmcnamara** [comment]
I've pushed a Python3 fix to master and tested it. 

You can try it and let me know.

**Comment by crisAD** [comment]
It worked from my side.
Thanks a lot!
Great help!
